[[CURRENCIES]]
code = "LEXX"
issuer = "rKGBPFzaFwB3LXiqDZjR3B5BjPVWDw4WqA"
display_decimals = 0

[METADATA]
token_name = "LEXX"
token_symbol = "LEXX"
total_supply = "14000000000"
issuer = "rKGBPFzaFwB3LXiqDZjR3B5BjPVWDw4WqA"
domain = "getlexxaicoin.com"
icon = "https://dancercasey.github.io/getlexxaicoin/logo.png"
