[METADATA]
token = "LEXX"
icon = "https://dancercasey.github.io/getlexxaicoin/logo.png"
description = "LEXX is a cross-chain asset bridging Stellar and XRPL."

[[CURRENCIES]]
code = "LEXX"
issuer = "rKGBPFzaFwB3LXiqDZjR3B5BjPVWDw4WqA"
display_decimals = 0
